// Default gamepad config — must match DEFAULT_CONFIG in src/types/gamepad.ts.
// Update both files together whenever the defaults change intentionally.
const DEFAULT_CONFIG = {
  mouseConfig: { mouseControls: 1, sensitivity: 10 },
  keyboardConfig: {
    Space: 'a',
    KeyB: 'b',
    Backspace: 'b',
    KeyY: 'y',
    KeyX: 'x',
    KeyQ: 'leftShoulder',
    KeyE: 'rightShoulder',
    RightClick: 'leftTrigger',
    Click: 'rightTrigger',
    BracketLeft: 'leftStickPressed',
    BracketRight: 'rightStickPressed',
    Enter: 'start',
    Tab: 'select',
    ArrowUp: 'dpadUp',
    ArrowDown: 'dpadDown',
    ArrowLeft: 'dpadLeft',
    ArrowRight: 'dpadRight',
    ShiftRight: 'rightTrigger',
    ShiftLeft: 'leftTrigger',
    KeyW: 'leftStickUp',
    KeyS: 'leftStickDown',
    KeyA: 'leftStickLeft',
    KeyD: 'leftStickRight',
    KeyO: 'rightStickUp',
    KeyL: 'rightStickDown',
    KeyK: 'rightStickLeft',
    Semicolon: 'rightStickRight',
    Backslash: 'home',
    F9: 'toggleGamepad',
  },
};

// Maps GamepadActionName → button index (standard gamepad mapping)
const ACTION_BUTTON_INDEX = {
  a: 0,
  b: 1,
  x: 2,
  y: 3,
  leftShoulder: 4,
  rightShoulder: 5,
  leftTrigger: 6,
  rightTrigger: 7,
  select: 8,
  start: 9,
  leftStickPressed: 10,
  rightStickPressed: 11,
  dpadUp: 12,
  dpadDown: 13,
  dpadLeft: 14,
  dpadRight: 15,
  home: 16,
};

// Maps GamepadActionName → { axisIndex, value }
const ACTION_AXIS = {
  leftStickLeft: { axisIndex: 0, value: -1 },
  leftStickRight: { axisIndex: 0, value: 1 },
  leftStickUp: { axisIndex: 1, value: -1 },
  leftStickDown: { axisIndex: 1, value: 1 },
  rightStickLeft: { axisIndex: 2, value: -1 },
  rightStickRight: { axisIndex: 2, value: 1 },
  rightStickUp: { axisIndex: 3, value: -1 },
  rightStickDown: { axisIndex: 3, value: 1 },
};

// Maps KeyboardEvent.code → Puppeteer key string
const CODE_TO_PUPPETEER_KEY = {
  Space: 'Space',
  Backspace: 'Backspace',
  Enter: 'Enter',
  Tab: 'Tab',
  ArrowUp: 'ArrowUp',
  ArrowDown: 'ArrowDown',
  ArrowLeft: 'ArrowLeft',
  ArrowRight: 'ArrowRight',
  ShiftLeft: 'ShiftLeft',
  ShiftRight: 'ShiftRight',
  F9: 'F9',
  Semicolon: 'Semicolon',
  KeyA: 'a',
  KeyB: 'b',
  KeyC: 'c',
  KeyD: 'd',
  KeyE: 'e',
  KeyF: 'f',
  KeyG: 'g',
  KeyH: 'h',
  KeyI: 'i',
  KeyJ: 'j',
  KeyK: 'k',
  KeyL: 'l',
  KeyM: 'm',
  KeyN: 'n',
  KeyO: 'o',
  KeyP: 'p',
  KeyQ: 'q',
  KeyR: 'r',
  KeyS: 's',
  KeyT: 't',
  KeyU: 'u',
  KeyV: 'v',
  KeyW: 'w',
  KeyX: 'x',
  KeyY: 'y',
  KeyZ: 'z',
  BracketLeft: '[',
  BracketRight: ']',
  Backslash: '\\',
};

module.exports = {
  DEFAULT_CONFIG,
  ACTION_BUTTON_INDEX,
  ACTION_AXIS,
  CODE_TO_PUPPETEER_KEY,
};
