// Default gamepad config — must match DEFAULT_CONFIG in src/types/gamepad.ts.
// Update both files together whenever the defaults change intentionally.
const DEFAULT_CONFIG = {
  mouseConfig: {
    mouseControls: [{ stick: 'right', gamepadIndex: 0, sensitivity: 101 }],
  },
  keyboardConfig: {
    Space: [{ type: 'action', gamepadIndex: 0, action: 'a' }],
    KeyB: [{ type: 'action', gamepadIndex: 0, action: 'b' }],
    Backspace: [{ type: 'action', gamepadIndex: 0, action: 'b' }],
    KeyY: [{ type: 'action', gamepadIndex: 0, action: 'y' }],
    KeyX: [{ type: 'action', gamepadIndex: 0, action: 'x' }],
    KeyQ: [{ type: 'action', gamepadIndex: 0, action: 'leftShoulder' }],
    KeyE: [{ type: 'action', gamepadIndex: 0, action: 'rightShoulder' }],
    RightClick: [{ type: 'action', gamepadIndex: 0, action: 'leftTrigger' }],
    Click: [{ type: 'action', gamepadIndex: 0, action: 'rightTrigger' }],
    BracketLeft: [
      { type: 'action', gamepadIndex: 0, action: 'leftStickPressed' },
    ],
    BracketRight: [
      { type: 'action', gamepadIndex: 0, action: 'rightStickPressed' },
    ],
    Enter: [{ type: 'action', gamepadIndex: 0, action: 'start' }],
    Tab: [{ type: 'action', gamepadIndex: 0, action: 'select' }],
    ArrowUp: [{ type: 'action', gamepadIndex: 0, action: 'dpadUp' }],
    ArrowDown: [{ type: 'action', gamepadIndex: 0, action: 'dpadDown' }],
    ArrowLeft: [{ type: 'action', gamepadIndex: 0, action: 'dpadLeft' }],
    ArrowRight: [{ type: 'action', gamepadIndex: 0, action: 'dpadRight' }],
    ShiftRight: [{ type: 'action', gamepadIndex: 0, action: 'rightTrigger' }],
    ShiftLeft: [{ type: 'action', gamepadIndex: 0, action: 'leftTrigger' }],
    KeyW: [{ type: 'action', gamepadIndex: 0, action: 'leftStickUp' }],
    KeyS: [{ type: 'action', gamepadIndex: 0, action: 'leftStickDown' }],
    KeyA: [{ type: 'action', gamepadIndex: 0, action: 'leftStickLeft' }],
    KeyD: [{ type: 'action', gamepadIndex: 0, action: 'leftStickRight' }],
    KeyO: [{ type: 'action', gamepadIndex: 0, action: 'rightStickUp' }],
    KeyL: [{ type: 'action', gamepadIndex: 0, action: 'rightStickDown' }],
    KeyK: [{ type: 'action', gamepadIndex: 0, action: 'rightStickLeft' }],
    Semicolon: [{ type: 'action', gamepadIndex: 0, action: 'rightStickRight' }],
    Backslash: [{ type: 'action', gamepadIndex: 0, action: 'home' }],
    F8: [{ type: 'action', gamepadIndex: 0, action: 'toggleGamepad' }],
  },
};

// Maps GamepadActionName → button index (standard gamepad mapping)
const ACTION_BUTTON_INDEX = {
  a: 0,
  b: 1,
  x: 2,
  y: 3,
  leftShoulder: 4,
  rightShoulder: 5,
  leftTrigger: 6,
  rightTrigger: 7,
  select: 8,
  start: 9,
  leftStickPressed: 10,
  rightStickPressed: 11,
  dpadUp: 12,
  dpadDown: 13,
  dpadLeft: 14,
  dpadRight: 15,
  home: 16,
};

// Maps GamepadActionName → { axisIndex, value }
const ACTION_AXIS = {
  leftStickLeft: { axisIndex: 0, value: -1 },
  leftStickRight: { axisIndex: 0, value: 1 },
  leftStickUp: { axisIndex: 1, value: -1 },
  leftStickDown: { axisIndex: 1, value: 1 },
  rightStickLeft: { axisIndex: 2, value: -1 },
  rightStickRight: { axisIndex: 2, value: 1 },
  rightStickUp: { axisIndex: 3, value: -1 },
  rightStickDown: { axisIndex: 3, value: 1 },
};

// Maps KeyboardEvent.code → Puppeteer key string
const CODE_TO_PUPPETEER_KEY = {
  Space: 'Space',
  Backspace: 'Backspace',
  Enter: 'Enter',
  Tab: 'Tab',
  ArrowUp: 'ArrowUp',
  ArrowDown: 'ArrowDown',
  ArrowLeft: 'ArrowLeft',
  ArrowRight: 'ArrowRight',
  ShiftLeft: 'ShiftLeft',
  ShiftRight: 'ShiftRight',
  F9: 'F9',
  Semicolon: 'Semicolon',
  KeyA: 'a',
  KeyB: 'b',
  KeyC: 'c',
  KeyD: 'd',
  KeyE: 'e',
  KeyF: 'f',
  KeyG: 'g',
  KeyH: 'h',
  KeyI: 'i',
  KeyJ: 'j',
  KeyK: 'k',
  KeyL: 'l',
  KeyM: 'm',
  KeyN: 'n',
  KeyO: 'o',
  KeyP: 'p',
  KeyQ: 'q',
  KeyR: 'r',
  KeyS: 's',
  KeyT: 't',
  KeyU: 'u',
  KeyV: 'v',
  KeyW: 'w',
  KeyX: 'x',
  KeyY: 'y',
  KeyZ: 'z',
  BracketLeft: '[',
  BracketRight: ']',
  Backslash: '\\',
};

module.exports = {
  DEFAULT_CONFIG,
  ACTION_BUTTON_INDEX,
  ACTION_AXIS,
  CODE_TO_PUPPETEER_KEY,
};
