import type { GamepadActionName } from '@/types/gamepad';

export const ACTION_LABELS: { action: GamepadActionName; label: string }[] = [
  { action: 'a', label: 'A' },
  { action: 'b', label: 'B' },
  { action: 'x', label: 'X' },
  { action: 'y', label: 'Y' },
  { action: 'leftShoulder', label: 'LB' },
  { action: 'rightShoulder', label: 'RB' },
  { action: 'leftTrigger', label: 'LT' },
  { action: 'rightTrigger', label: 'RT' },
  { action: 'select', label: 'Select' },
  { action: 'start', label: 'Start' },
  { action: 'dpadUp', label: 'D-Up' },
  { action: 'dpadDown', label: 'D-Down' },
  { action: 'dpadLeft', label: 'D-Left' },
  { action: 'dpadRight', label: 'D-Right' },
  { action: 'leftStickPressed', label: 'LS Press' },
  { action: 'rightStickPressed', label: 'RS Press' },
  { action: 'leftStickUp', label: 'LS Up' },
  { action: 'leftStickDown', label: 'LS Down' },
  { action: 'leftStickLeft', label: 'LS Left' },
  { action: 'leftStickRight', label: 'LS Right' },
  { action: 'rightStickUp', label: 'RS Up' },
  { action: 'rightStickDown', label: 'RS Down' },
  { action: 'rightStickLeft', label: 'RS Left' },
  { action: 'rightStickRight', label: 'RS Right' },
  { action: 'home', label: 'Home' },
  { action: 'toggleGamepad', label: 'Toggle Gamepad' },
];
