import type { GamepadActionName } from '@/types/gamepad';

export const ACTION_NAMES: GamepadActionName[] = [
  'a',
  'b',
  'x',
  'y',
  'leftShoulder',
  'rightShoulder',
  'leftTrigger',
  'rightTrigger',
  'select',
  'start',
  'dpadUp',
  'dpadDown',
  'dpadLeft',
  'dpadRight',
  'leftStickPressed',
  'rightStickPressed',
  'leftStickUp',
  'leftStickDown',
  'leftStickLeft',
  'leftStickRight',
  'rightStickUp',
  'rightStickDown',
  'rightStickLeft',
  'rightStickRight',
  'home',
];

export const ACTION_LABEL: Record<GamepadActionName, string> = {
  a: 'A',
  b: 'B',
  x: 'X',
  y: 'Y',
  leftShoulder: 'LB',
  rightShoulder: 'RB',
  leftTrigger: 'LT',
  rightTrigger: 'RT',
  select: 'Select',
  start: 'Start',
  dpadUp: 'D-Up',
  dpadDown: 'D-Down',
  dpadLeft: 'D-Left',
  dpadRight: 'D-Right',
  leftStickPressed: 'LS Press',
  rightStickPressed: 'RS Press',
  leftStickUp: 'LS Up',
  leftStickDown: 'LS Down',
  leftStickLeft: 'LS Left',
  leftStickRight: 'LS Right',
  rightStickUp: 'RS Up',
  rightStickDown: 'RS Down',
  rightStickLeft: 'RS Left',
  rightStickRight: 'RS Right',
  home: 'Home',
  toggleGamepad: 'Toggle Gamepad',
  toggleAllGamepads: 'Toggle All Gamepads',
  toggleExtension: 'Toggle Extension',
};

export const TYPE_OPTIONS = [
  { value: 'tap', text: 'Tap' },
  { value: 'turbo', text: 'Turbo' },
  { value: 'hold', text: 'Hold' },
  { value: 'suspend', text: 'Suspend' },
  { value: 'loop', text: 'Repeat' },
  { value: 'loop_forever', text: 'Forever' },
  { value: 'delay', text: 'Delay' },
  { value: 'down', text: 'Press Key' },
  { value: 'up', text: 'Release Key' },
];

export const ACTION_OPTIONS = ACTION_NAMES.map((a) => ({
  value: a,
  text: ACTION_LABEL[a],
}));
